fragment BlogParts on Blog {
  __typename
  title
  description
  author
  date
  topics
  featuredImage
  featured
  body
}

fragment ConveniosParts on Convenios {
  __typename
  name
  slug
  description
  address
  phone
  googleMapsUrl
  logo
  gallery
  featured
  cities
  areas
  benefitTypes
  clientProfiles
  benefitSummary
  body
}
