export const WHATSAPP_LEAD_CITIES = [
  "Piracicaba",
  "Americana",
  "Santa Bárbara d'Oeste",
  "Limeira",
  "São Pedro",
  "Águas de São Pedro",
  "Charqueada",
  "Rio Claro",
  "Campinas",
  "Nova Odessa",
  "Sumaré",
  "Paulínia",
  "Capivari",
  "Ipeúna",
  "Santa Maria da Serra",
  "Saltinho",
  "Tietê",
  "Outra cidade",
] as const;
